# Generated by Django 4.2.13 on 2024-06-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='cabin',
            new_name='Cabin',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='embarked',
            new_name='Embarked',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='fare',
            new_name='Fare',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='parch',
            new_name='Parch',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='passenger_id',
            new_name='PassengerId',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='pclass',
            new_name='Pclass',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='sex',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='sibsp',
            new_name='SibSp',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='survived',
            new_name='Survived',
        ),
        migrations.RenameField(
            model_name='titanic',
            old_name='ticket',
            new_name='Ticket',
        ),
    ]
