# Generated by Django 4.2.13 on 2024-06-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_titanic_id_alter_titanic_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
